# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-16 20:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='photo',
            new_name='upload_photo',
        ),
    ]
