# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-19 19:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_auto_20171217_0307'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload_photo',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
